name: aad_oauth
description: A Flutter OAuth package for performing user authentication against
  Azure Active Directory OAuth2 v2.0 endpoint.
version: 0.3.1
homepage: https://github.com/Earlybyte/aad_oauth

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.2.0
  http: ^0.13.3
  pedantic: ^1.11.1
  shared_preferences: ^2.0.11
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
